### ISSUE TITLE
Cleanup and push to crates.io

### ISSUE THREAD

**Issue by wmedrano** [wmedrano/lilv-rs#1]
I'd like to have the library in a cleaner state and pushed to crates.io so I can use it in my own project. Should I make some changes and push them to this repo or should I maintain my own fork?

I would like to:
  1. Follow the Rust API guidelines: https://rust-lang.github.io/api-guidelines/
  2. Depend on lilv-sys for the ffi definitions
  3. Split Instance into Instance and ActivatedInstance
  4. Add docs + testing

**Comment by grejppi** [comment]
Hey sorry I haven't even seen this issue! This repo didn't have notifications on for whatever reason.

I also ended up maintaining my own copy (and eventually, rewrite) of this code in my project because keeping up with so many repositories was getting tedious and there were lots of other issues with the greater whole. Now that most of them have been resolved I've now updated this repo with that newer code.

Anyway as for the changes:

> Follow the Rust API guidelines: https://rust-lang.github.io/api-guidelines/

There are no `get_` prefixes anymore for methods, but that's all I can say for certain😆 I haven't paid much more attention to the API at this point yet.

> Depend on lilv-sys for the ffi definitions

This has been done.

> Split Instance into Instance and ActivatedInstance

Could you please explain this idea or its rationale more? This does sound like how clients work in the `jack` crate so it would make sense in that way, but I haven't really understood its reasoning either yet😅

> Add docs + testing

Yes, this is obviously needed. I've added two examples however, a port of `lv2ls` and a WIP port of `lv2info` that currently lists info for all plugins.

**Comment by wmedrano** [comment]
Done.
